from . import project_task
from . import project_update
from . import res_partner
from . import project
from . import sale_line
from . import project_sub_update
from . import sale_order
from . import project_tags
from . import supervisor
from . import pending_service
from . import employee
from . import asignar_avances_project_wizard
from . import hr_employee
from . import control_centro_trabajo
from . import control_planta
from . import dashboard_sale_order
from . import product_template
from . import project_task_type
from . import purchase_order
from . import dashboard_project
from . import dashboard_task
from . import hr_expense
from . import wizard_rechazado_task
from . import project_profitability_report
from . import stock
